---
- name: download consul
  unarchive:
    src: https://releases.hashicorp.com/consul/1.0.1/consul_1.0.1_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes

- name: service copy
  template:
    src: service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: enable service
  systemd:
    name: consul
    enabled: yes

- name: install dnsmasq
  yum:
    name: dnsmasq
    state: installed

- name: enable service
  systemd:
    name: dnsmasq
    enabled: yes
