---
- name: install jdk
  yum:
    name: java-1.8.0-openjdk-devel
    state: installed

- name: install maven
  unarchive:
    src: http://www-eu.apache.org/dist/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
    dest: /usr/local
    remote_src: yes

- name: move maven
  shell: mv /usr/local/apache-maven-3.5.2 /usr/local/maven

# - name: run maven
#   command: /usr/local/maven/bin/mvn -f /tmp/pom.xml test

#
# - name:
#   file:
#     path: /home/vagrant/.m2
#     owner: vagrant
#     group: vagrant
#     recurse: yes
#     state: directory

- name: service copy
  template:
    src: app-service.j2
    dest: /etc/systemd/system/app.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: enable service
  systemd:
    name: app
    enabled: yes

- name: create directory
  file:
    dest: /root/.m2
    state: directory

- name: copy settings.xml
  template:
    src: settings.j2
    dest: /root/.m2/settings.xml
    owner: root
    group: root

- name: run maven
  command: /usr/local/maven/bin/mvn -f /tmp/pom.xml -s /root/.m2/settings.xml test
